
{"xxx", "XML Formatter", "XmlFormatter"},
{"xxx", "JSON Formatter", "JsonFormatter"},
{"xxx", "YAML Formatter", "YamlFormatter"},
{"xxx", "Date Time Util", "DateTimeUtil"},
{"xxx", "Base64 Encode Decode", "Base64EncodeDecode"},
{"xxx", "Regex Content Generator", "RegExContentGen"},
{"xxx", "Random Password Generator", "RandomPasswordGen"},
{"xxx", "Telnet Tool", "Telnet"},
{"xxx", "Windows Settings", "WindowsSettings"},
{"xxx", "Hosts Editor (Table)", "HostsEditor"},
{"xxx", "Hosts Editor (Text)", "SimpleHostsEditor"},
{"xxx", "Ping Tool", "Ping"},
{"xxx", "Network Scanner", "NetworkScanner"},
{"xxx", "Database Tool", "DatabaseTool"},
{"xxx", "IP Lookup Tool", "IpLookupTool"},
{"xxx", "PDF Merge", "PdfMerge"},
{"xxx", "Regex Test Tool", "RegExTest"},
{"xxx", "Image Compression", "ImageCompression"},
{"xxx", "Favicon Production", "FaviconProduction"},
{"xxx", "Color Tools", "ColorTools"},
{"xxx", "Mobile Location", "MobileLocation"},
{"xxx", "HTML Special Character Table", "HtmlSpecialCharacterTable"},
{"xxx", "Torrent File Analysis", "TorrentFileAnalysis"},
{"xxx", "Zip Code Query", "ZipCodeQuery"},
{"xxx", "QR Code Generator", "QrCodeGen"},
{"xxx", "Image Text Recognition", "ImageTextRecognition"},
{"xxx", "File Hash Calculation", "FileHashCalculation"},
{"xxx", "Barcode Generator", "BarcodeGen"},
{"xxx", "Image Format Conversion", "ImageFormatConversion"},
{"xxx", "HTTP Status Code", "HttpStatusCode"},
{"xxx", "Crontab Time Calculation", "CrontabTimeCalculation"},
{"xxx", "Text Encryption And Decryption", "TextEncryptionAndDecryption"},
{"xxx", "UUID Generator", "UuidGen"},
{"xxx", "OpenCV Demo", "OpenCvDemo"},
{"xxx", "OpenCV Image Processor", "OpenCvImageProcessor"},
{"xxx", "SSH Client", "SSHClient"},
{"xxx", "FTP Client", "FTPClient"},
{"xxx", "FTP Server", "FTPServer"},
{"xxx", "Camera Tool", "CameraTool"},
{"xxx", "Terminal Tool", "TerminalTool"},
{"xxx", "Traceroute Tool", "TracerouteTool"},
{"xxx", "Route Test Tool", "RouteTestTool"},
{"xxx", "System Info Tool", "SystemInfoTool"},
{"xxx", "Rich Text Notepad", "Notepad"},
{"xxx", "Media Manager", "MediaManager"},
{"xxx", "Image Watermark", "ImageWatermark"},
{"xxx", "WHOIS Tool", "WhoisTool"},
{"xxx", "File Compare Tool", "FileCompareTool"},
{"xxx", "Blood Type Tool", "BloodTypeTool"},
{"xxx", "Port Scanner", "PortScanner"},
{"xxx", "Key Remapper", "KeyRemapper"},
{"xxx", "Chinese Copybook", "ChineseCopybook"},
